# Generated by Django 5.2.10 on 2026-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="payments_st_event_t_af3af6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(
                fields=["status", "created_at"], name="payments_st_status_f12f17_idx"
            ),
        ),
    ]
