# Generated by Django 5.2.10 on 2026-01-16 01:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshotDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("orders", models.PositiveIntegerField(default=0)),
                (
                    "aov",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("refunded_orders", models.PositiveIntegerField(default=0)),
                ("unique_customers", models.PositiveIntegerField(default=0)),
                ("repeat_customers", models.PositiveIntegerField(default=0)),
                ("wish_users", models.PositiveIntegerField(default=0)),
                ("purchased_users", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-day"],
            },
        ),
    ]
