# Generated by Django 5.2.10 on 2026-01-16 01:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyticsapp", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsProductDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("units", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_analytics",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-day", "-revenue"],
                "indexes": [
                    models.Index(fields=["day"], name="analyticsap_day_ff1439_idx"),
                    models.Index(
                        fields=["product"], name="analyticsap_product_1bdf52_idx"
                    ),
                    models.Index(
                        fields=["day", "product"], name="analyticsap_day_815a8b_idx"
                    ),
                ],
                "unique_together": {("day", "product")},
            },
        ),
    ]
