# Generated by Django 5.2.10 on 2026-01-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("analyst", "Analyst"),
                    ("ops", "Operations"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
