# Generated by Django 5.2.10 on 2026-01-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("payment_mismatch", "Payment Mismatch"),
                            ("stock_anomaly", "Stock Anomaly"),
                            ("order_state", "Invalid Order State"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reference_id", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
    ]
