# Generated by Django 5.2.10 on 2026-01-13 23:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataqualityissue",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="dataqualityissue",
            unique_together={("issue_type", "reference_id")},
        ),
        migrations.AddField(
            model_name="dataqualityissue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataqualityissue",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dataqualityissue",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataqualityissue",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataqualityissue",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("resolved", "Resolved")],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dataqualityissue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("payment_mismatch", "Payment mismatch"),
                    ("missing_stripe_ref", "Missing Stripe reference"),
                    ("stock_anomaly", "Stock anomaly"),
                    ("invalid_order_state", "Invalid order state"),
                    ("amount_mismatch", "Amount mismatch"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="reference_id",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="dataqualityissue",
            name="detected_at",
        ),
        migrations.RemoveField(
            model_name="dataqualityissue",
            name="resolved",
        ),
    ]
