# Generated by Django 5.2.10 on 2026-01-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_normalize_issue_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualityissue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("payment_mismatch", "Payment mismatch"),
                    ("missing_stripe_ref", "Missing Stripe reference"),
                    ("stock_anomaly", "Stock anomaly"),
                    ("invalid_order_state", "Invalid order state"),
                    ("amount_mismatch", "Amount mismatch"),
                    (
                        "analytics_snapshot_reconciliation",
                        "Analytics snapshot reconciliation",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
