# Generated by Django 5.2.10 on 2026-01-27 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_dataqualityissue_issue_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataqualityissue',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='dataqualityissue',
            index=models.Index(fields=['-created_at'], name='dqissue_created_desc'),
        ),
        migrations.AddIndex(
            model_name='dataqualityissue',
            index=models.Index(fields=['status'], name='dqissue_status'),
        ),
        migrations.AddIndex(
            model_name='dataqualityissue',
            index=models.Index(fields=['issue_type'], name='dqissue_type'),
        ),
        migrations.AddIndex(
            model_name='dataqualityissue',
            index=models.Index(fields=['reference_id'], name='dqissue_ref'),
        ),
        migrations.AddConstraint(
            model_name='dataqualityissue',
            constraint=models.UniqueConstraint(fields=('issue_type', 'reference_id'), name='uq_dqissue_type_ref'),
        ),
    ]
