# Generated by Django 5.2.10 on 2026-01-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderitem_product_orderitem_variant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="refund_amount_pennies",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[("none", "None"), ("partial", "Partial"), ("full", "Full")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
