# Generated by Django 5.2.10 on 2026-01-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_refund_amount_pennies_and_more'),
    ]

    operations = [
    ]
