# Generated by Django 5.2.10 on 2026-01-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_normalize_canceled_spelling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("fulfilled", "Fulfilled"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
